#!/usr/bin/env node

var serialport = require('serialport'),
	SerialPort = serialport.SerialPort;

// Setup the TTY serial port
var tty = new SerialPort('/dev/ttyO1', { 
    parser: serialport.parsers.readline("\n")
});

tty.on('data',function(data){
	try {
		var device = JSON.parse(data);
	} catch (err) { return; }
	if (device.ACK && device.ACK[0].D===1003) {
		process.stdout.write(device.ACK[0].DA);
		process.exit(0);
	}
});

tty.write('{"DEVICE":[{"G":"0","V":0,"D":1003,"DA":"VNO"}]}');